### ISSUE TITLE
Specify the difference between unit test and Test driven development

### ISSUE THREAD

**Issue by nokiiam** [KoltesDigital/Game-Architecture-Epita-2019#1]
In the two summary the "Unit test" part talk more about the principle behind the Test Driven Development which used unit testing instead of unit test itself. It should be a good idea to make the distinction between the two or change the name of this part to not confused people between the two.

**Comment by KoltesDigital** [comment]
Thanks! Is 05ae12fd847d0c4867f69b5b0f71e50d8d0d2cb1 better?
